=================================
How to Use 101-lazy_matrix_mul.py
=================================

This module defines a matrix multiplication function
``lazy_matrix_mul(m_a, m_b)``.

Usage
=====

``lazy_matrix_mul(...)`` returns a new matrix representing the multiplication
of ``m_a`` by ``m_b``.


>>> lazy_matrix_mul = __import__('101-lazy_matrix_mul').lazy_matrix_mul

>>> lazy_matrix_mul()
Traceback (most recent call last):
TypeError: lazy_matrix_mul() missing 2 required positional arguments: 'm_a' and 'm_b'

>>> lazy_matrix_mul([[1, 2], [3, 4]])
Traceback (most recent call last):
TypeError: lazy_matrix_mul() missing 1 required positional argument: 'm_b'

>>> lazy_matrix_mul([[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 20], [211, 12]])
Traceback (most recent call last):
TypeError: lazy_matrix_mul() takes 2 positional arguments but 3 were given

=============================================

>>> print(lazy_matrix_mul([[]], [[5, 6], [7, 8]]))
Traceback (most recent call last):
ValueError: shapes (1,0) and (2,2) not aligned: 0 (dim 1) != 2 (dim 0)


>>> print(lazy_matrix_mul([[1, 2], [3, 4]], [[]]))
Traceback (most recent call last):
ValueError: shapes (2,2) and (1,0) not aligned: 2 (dim 1) != 1 (dim 0)

>>> print(lazy_matrix_mul("not list", [[1, 2]]))
Traceback (most recent call last):
ValueError: Scalar operands are not allowed, use '*' instead

>>> print(lazy_matrix_mul([[1, 2]], "not list"))
Traceback (most recent call last):
ValueError: Scalar operands are not allowed, use '*' instead

>>> print(lazy_matrix_mul("not list", "not list"))
Traceback (most recent call last):
ValueError: Scalar operands are not allowed, use '*' instead


>>> print(lazy_matrix_mul(None, None))
Traceback (most recent call last):
TypeError: Object arrays are not currently supported

>>> print(lazy_matrix_mul([1, 2], [[3, 4]]))
Traceback (most recent call last):
ValueError: shapes (2,) and (1,2) not aligned: 2 (dim 0) != 1 (dim 0)


>>> print(lazy_matrix_mul([[1, 4]], [3, 4]))
[19]

>>> print(lazy_matrix_mul([1, 4], [3, 4]))
19

>>> print(lazy_matrix_mul([[1, 2], [3, 4]], [[5, "6"], [7, 8]]))
Traceback (most recent call last):
TypeError: invalid data type for einsum

>>> m_a = [
... [1, 2],
... [3, 4, 5]
... ]
>>> m_b = [
... [1, 2],
... [3, 4]
... ]
>>> print(lazy_matrix_mul(m_a, m_b))
Traceback (most recent call last):
ValueError: setting an array element with a sequence.
